CREATE DATABASE global_ecommerce_sales;
USE global_ecommerce_sales;

SELECT *FROM global_ecommerce_sales
LIMIT 10;

-- How many orders are there in the dataset?

SELECT COUNT(*) AS total_orders
FROM global_ecommerce_sales;

-- What is the total revenue?

SELECT SUM(Total_Amount) AS total_revenue
FROM global_ecommerce_sales;

-- What is the average order value?

SELECT ROUND(AVG(Total_Amount),2) AS average_order_value
FROM global_ecommerce_sales;

-- Show top 5 highest orders.

SELECT Order_ID,
Country,
Category,
Total_Amount
FROM global_ecommerce_sales
ORDER BY Total_Amount DESC
LIMIT 5;

-- Show the lowest order.

SELECT Order_ID,
Country,
Category,
Total_Amount
FROM global_ecommerce_sales
ORDER BY Total_Amount
LIMIT 1;

-- How many countries are present

SELECT COUNT(DISTINCT Country) AS total_countries
FROM global_ecommerce_sales;

-- How many product categories are there?

SELECT COUNT(DISTINCT Category) AS total_categories
FROM global_ecommerce_sales;

-- Which country has the highest sales?

SELECT Country,
SUM(Total_Amount) AS total_sales
FROM global_ecommerce_sales
GROUP BY Country
ORDER BY total_sales DESC
LIMIT 5;

-- Which category has the highest sales?

SELECT Category,
SUM(Total_Amount) AS total_sales
FROM global_ecommerce_sales
GROUP BY Category
ORDER BY total_sales DESC;

-- Which category sold the highest quantity?

SELECT Category,
SUM(Quantity) AS total_quantity
FROM global_ecommerce_sales
GROUP BY Category
ORDER BY total_quantity DESC;

-- Show all orders where quantity is greater than 5.

SELECT *
FROM global_ecommerce_sales
WHERE Quantity > 5;

-- Show orders where Total Amount is more than 1000.

SELECT *
FROM global_ecommerce_sales
WHERE Total_Amount > 1000;

-- Show all orders from India.

SELECT *
FROM global_ecommerce_sales
WHERE Country = 'India';

-- Find the average quantity sold in each category.

SELECT Category,
AVG(Quantity) AS average_quantity
FROM global_ecommerce_sales
GROUP BY Category;

-- Find the total revenue generated by each country.

SELECT Country,
SUM(Total_Amount) AS total_revenue
FROM global_ecommerce_sales
GROUP BY Country
ORDER BY total_revenue DESC;

-- Show the top 3 countries with the highest revenue.

SELECT Country,
SUM(Total_Amount) AS total_revenue
FROM global_ecommerce_sales
GROUP BY Country
ORDER BY total_revenue DESC
LIMIT 3;

-- Find the highest Unit Price.

SELECT MAX(Unit_Price) AS highest_price
FROM global_ecommerce_sales;

-- Find the lowest Unit Price.

SELECT MIN(Unit_Price) AS lowest_price
FROM global_ecommerce_sales;

-- Find the average Unit Price.

SELECT ROUND(AVG(Unit_Price),2) AS average_price
FROM global_ecommerce_sales;

-- Show the total quantity sold in each country.

SELECT Country,
SUM(Quantity) AS total_quantity
FROM global_ecommerce_sales
GROUP BY Country
ORDER BY total_quantity DESC;

-- Which categories have total sales greater than 50,000?

SELECT Category,
SUM(Total_Amount) AS total_sales
FROM global_ecommerce_sales
GROUP BY Category
HAVING SUM(Total_Amount) > 50000;

-- Show all orders sorted by Order Date.

SELECT *
FROM global_ecommerce_sales
ORDER BY Order_Date;

-- Find monthly revenue.

SELECT 
    MONTHNAME(Order_Date) AS month_name,
    SUM(Total_Amount) AS total_revenue
FROM
    global_ecommerce_sales
GROUP BY MONTH(Order_Date) , MONTHNAME(Order_Date)
ORDER BY MONTH(Order_Date);

-- Classify orders as High, Medium and Low Sales.

SELECT Order_ID,
Total_Amount,
CASE
    WHEN Total_Amount >= 1000 THEN 'High Sales'
    WHEN Total_Amount >= 500 THEN 'Medium Sales'
    ELSE 'Low Sales'
END AS Sales_Category
FROM global_ecommerce_sales;

-- Rank countries based on total revenue.

SELECT Country,
SUM(Total_Amount) AS total_revenue,
RANK() OVER(ORDER BY SUM(Total_Amount) DESC) AS country_rank
FROM global_ecommerce_sales
GROUP BY Country;

-- Top 5 Expensive Products

SELECT *
FROM global_ecommerce_sales
ORDER BY Unit_Price DESC
LIMIT 5;

-- Lowest Revenue Country

SELECT Country,
SUM(Total_Amount) AS Revenue
FROM global_ecommerce_sales
GROUP BY Country
ORDER BY Revenue ASC
LIMIT 1;

-- Total Sales by Category

SELECT Category,
COUNT(*) AS Total_Orders
FROM global_ecommerce_sales
GROUP BY Category;

-- Highest Quantity Order

SELECT *
FROM global_ecommerce_sales
ORDER BY Quantity DESC
LIMIT 1;

